cancervariants/therapy-normalization

therapy/models.py
With https://github.com/cancervariants/therapy-normalization/pull/9/commits/464893ba4379fa11f3fa9d483a063862a954b368 the label might be null, which would cause an error if that field isn't optional.
=> Make drug label optional

therapy/database.py, therapy/query.py
Noticed that I left an arg for forcing table creation in when it had been removed -- now, the db should automatically try to create tables if you give it an endpoint that isn't the AWS cloud (i.e. something local). We could also make it an explicit option, though.
=> Pull out table creation logic that was causing errors

therapy/main.py, therapy/query.py
`q = 'cisplatin'` returns a match but `q='cisplatin     '` does not.
=> fix normalize endpoint bug

tests/unit/data/test_query_data.json, tests/unit/data/therapies.json, tests/unit/test_query.py, therapy/main.py, therapy/query.py, therapy/schemas.py
Close #263 
* Add endpoint that provides normalized concept group data but doesn't merge to a single ValueObject Descriptor 
This is needed for DGIdb and the same feature is required for genes, so we should settle on the shape of the output here to keep them consistent
=> feat: add unmerged normalize endpoint (#263)

setup.cfg, tests/unit/data/therapies.json, tests/unit/test_wikidata.py, therapy/etl/base.py, therapy/etl/manual_override.csv, therapy/etl/rules.py
close #269 
close #294 
As implemented, this just makes a simple framework for declaring prohibited values on specific fields for specific concepts. IE, if I enter a row in rules.csv, I'm saying "don't allow this value to be entered for this record".
I didn't do this work, but it could pretty easily expanded to add an `add/remove` column (ie, if that column says `add`, then add that value in that field for that record), or to handle the non-scalar properties eg labels.
=> feat: add manual data extraction override rules

.github/workflows/checks.yaml, tests/conftest.py, tests/scripts/build_disease_normalizer_data.py, tests/unit/test_disease_indication.py, therapy/etl/base.py, therapy/version.py
Close #340 
Ugh sorry. Forgot that disease normalizer was monkey patched for CI tests, so thought I could get away with not running all the ETL methods. 🤦‍♀️  Going to run them now 😅 
I also removed a TODO from the build_disease_normalizer_data
=> fix: Add test for DiseaseIndicationBase

.github/workflows/release.yml
* Followed https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
* Did not include [Signing the distribution packages](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages)
* In `publish-to-pypi`, removed `if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes` since we only make a release when a GH release is created.
=>  cicd: update release.yml (publish python distribution to pypi)

src/therapy/etl/hemonc.py
=> fix: handle hemonc deprecated concept

.pre-commit-config.yaml, pyproject.toml, src/therapy/__init__.py, src/therapy/cli.py, src/therapy/etl/__init__.py, src/therapy/etl/base.py, src/therapy/etl/chemidplus.py, src/therapy/etl/drugbank.py, src/therapy/etl/drugsatfda.py, src/therapy/etl/guidetopharmacology.py, src/therapy/etl/hemonc.py, src/therapy/etl/ncit.py, src/therapy/etl/rxnorm.py, src/therapy/main.py, src/therapy/schemas.py, tests/unit/test_database.py, tests/unit/test_guidetopharmacology.py, tests/unit/test_ncit.py, tests/unit/test_query.py, tests/unit/test_wikidata.py
Somehow I managed to do this wrong, in a different way, on each repo
edit: actually did a few other things
* removed a bunch of `noqa` annotations for checks that we weren't using
* configured lint rules for updated compatibility with formatter, see https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
* cleaned up a few small unused/unrelated things
=> style: fix ruff settings

src/therapy/etl/base.py
Originally we used `lru_cache` to try it out, but with the volume of disease terms we end up using I don't think there's any reason not to just cache the whole thing in a dict.
=> perf: improve disease caching

src/therapy/cli.py, src/therapy/version.py
I'm working on updating ddb updates for therapy. It would be useful to see ETL progress in CW logs.
=> feat: set silent to False in CLI

README.md, src/therapy/version.py
close #399 
Location in wags-tails: https://github.com/GenomicMedLab/wags-tails/blob/main/src/wags_tails/hemonc.py#L79
=> docs: fix env var name for harvard dataverse api key

pyproject.toml
I think we just didn't have any disease-specific dependencies before, but now, if you try to trigger disease updates from the therapy side, you'll hit an import error for `fastobo`, which is only used for Mondo.
=> build: get disease ETL dependencies

pyproject.toml, src/therapy/cli.py, src/therapy/etl/base.py, src/therapy/etl/chembl.py, src/therapy/etl/chemidplus.py, src/therapy/etl/drugbank.py, src/therapy/etl/drugsatfda.py, src/therapy/etl/guidetopharmacology.py, src/therapy/etl/hemonc.py, src/therapy/etl/merge.py, src/therapy/etl/ncit.py, src/therapy/etl/rxnorm.py, src/therapy/etl/wikidata.py
**Situation**: Updating the therapy normalizer locally takes a lot of time, particularly the ChEMBL import and normalized group generation. It can be hard to tell if the process is hung or not.
**Background**: Refreshing TheraPy is needed to create new data releases for DGIdb. This is done locally because it's not yet feasible to automate this process on the DGIdb server (would need a few new features from Thera-Py and some DGIdb scripting).
**Assessment**: Progress bars are an easy drop-in way to tell that import processes are continuing to progress.
**Recommendation**: Use TQDM where possible to show progress, and `rich.Status` otherwise.
close #312
=> feat: add progress bars/indicators to CLI ETL processes

src/therapy/query.py
this was remarkably annoying to track down. It should fix https://github.com/cancervariants/metakb/issues/347
=> fix: use enum for source name to ensure proper pydantic serialization

.github/workflows/checks.yaml
forgot to change this in a previous PR, but also, this is the only repo where we do linting across all these versions and it's probably not necessary
=> cicd: only lint in 3.11

.github/workflows/checks.yaml, pyproject.toml
I still think it's helpful to run locally from time to time but I don't think it's efficient to be performing this check on only this repo. If we want to revisit, we should do so for all of our projects.
=> cicd: remove mypy checks

src/therapy/cli.py, src/therapy/log.py
Largely a copy/paste of work done in metakb. Small QOL increase for running data updates.
Some follow up refactoring to do for CLI commands and where data update modules live. There's also a way to configure FileHandlers to support a full custom path but I don't think that's a priority.
=> feat: properly configure logging in cli

pyproject.toml, src/therapy/etl/base.py, src/therapy/main.py, src/therapy/query.py, src/therapy/schemas.py, tests/data/fixtures/query_fixtures.json, tests/unit/test_query.py
close #448 
* Update modules to vrs [2.0.0-ballot.2024-11.3](https://github.com/ga4gh/vrs/tree/2.0.0-ballot.2024-11.3) tag
* Use preferred formats for `MappableConcept.mappings`
* `system` will use OBO Foundry persistent URL (PURL), source homepage,
or namespace prefix, in that order of preference, if available.
* `code` will use the `concept_id` as the CURIE
* Remove `normalized_id` and leverage `MappableConcept.primaryCode`
* Also updates mappings to include exactMatch relation for merged concept identifier  
* Therapeutic Agent --> Therapy
=> feat!: update models to vrs 2.0.0 community review ballot

pyproject.toml
Forgot to add this in #449 🤦‍♀️ Disease normalizer is now required since we use its schemas in the QueryHandler
I'm wondering if we should consider updating cicd tests to install minimal deps needed to help prevent bugs like this in the future
=> fix(build): add disease-normalizer as required dep

pyproject.toml, src/therapy/query.py, src/therapy/schemas.py, tests/conftest.py, tests/data/fixtures/query_fixtures.json
close #456
* bump disease normalizer version to pull in updated system IRIs
* correct `Coding` representation
* `system` MUST use `iriReference`, not a free-text label
* `code` MUST use syntax defined by the `system`
* `id` will use record `concept_id`
* Removes `SYSTEM_URI_TO_NAMESPACE` mapping (since it's no longer needed)
=> fix!: use correct representation of Coding object in mappings

src/therapy/query.py
close #458
* `source_meta` key should have type `SourceName` not `str`
=> fix: resolve pydantic serializer warnings in `_add_merged_meta`

pyproject.toml
Ensure interoperability and avoid issues stemming from earlier VRS-Python releases
=> build: tighten VRS-Python version restriction

src/therapy/cli.py
I don't have an idea for another filter like with the other normalizers, but this PR adds the description object to show what parameters were used to create the document (for the sake of consistency)
=> feat: add description to mappings document
