cancervariants/therapy-normalization

- therapy/models.py
- therapy/normalizers/chembl.py
- therapy/query.py
This is a catchall PR to cover various bugs and feature additions we talked about (see commit list for details). I did include  a change to make the normalizer matches a dict keyed on the normalizer name. I understand that you wanted that to be an option so that's still something TODO. The current version is what is needed for the new DGIdb drug grouper to work.
> Various updates to the ChEMBL normalizer

- .gitignore
Updating gitignore to exclude local IDE-related files for Vim, PyCharm
> update gitignore IDE-related conditions

- cli.py
- main.py
Add/change description text as it appears on the root docs page
> Swagger docs

- main.py
Change endpoints for API Gateway
> API Gateway

- dynamodb_revisions/update_meta.py
- tests/unit/data/metadata.json
- tests/unit/test_chembl_source.py
- tests/unit/test_drugbank_source.py
- tests/unit/test_ncit_source.py
- tests/unit/test_wikidata_source.py
- therapy/etl/chembl.py
- therapy/etl/drugbank.py
- therapy/etl/ncit.py
- therapy/etl/wikidata.py
- therapy/schemas.py
We should bundle `share_alike`, `non_commercial`, `attribution` under the `data_license_attributes` field.
> Create data_license_attributes field

- tests/unit/data/therapies.json
- tests/unit/test_rxnorm_source.py
- therapy/etl/rxnorm.py
- Create link for brand names and its concept id
- Add precise ingredients as identity concepts
> RxNorm Brand Names and Precise Ingredients

- tests/unit/data/therapies.json
- tests/unit/test_merge.py
- tests/unit/test_query.py
- tests/unit/test_wikidata_source.py
- therapy/etl/merge.py
pending confirmation that duplicates are no longer being created
> Issue 62 idfix

- dynamodb_revisions/README.md
- dynamodb_revisions/delete_merged_records.py
- dynamodb_revisions/update_xrefs_other_ids.py
> Delete merge records

- cli.py
We can always add this back in for #91 .
> Remove merge creation from CLI

- README.md
- tests/unit/test_database.py
- therapy/cli.py
- therapy/database.py
> Change default db endpoint to localhost

- README.md
- setup.py
- tests/conftest.py
- tests/unit/data/therapies.json
- tests/unit/test_chembl_source.py
- tests/unit/test_chemidplus_source.py
- tests/unit/test_database.py
- tests/unit/test_drugbank_source.py
- tests/unit/test_merge.py
- tests/unit/test_ncit_source.py
- tests/unit/test_query.py
- tests/unit/test_rxnorm_source.py
- tests/unit/test_wikidata_source.py
- therapy/__init__.py
- therapy/database.py
- therapy/etl/chemidplus.py
- therapy/etl/drugbank.py
- therapy/etl/merge.py
- therapy/etl/ncit.py
- therapy/etl/rxnorm.py
- therapy/etl/wikidata.py
- therapy/main.py
- therapy/query.py
- therapy/schemas.py
Combining other_id references + the VOD update so we only have to merge the issue-90 stuff once
> Other id ref

- setup.py
- therapy/__init__.py
- therapy/cli.py
> fix update_all error

- setup.py
- therapy/__init__.py
- therapy/query.py
> Fix sources bug

- tests/unit/test_query.py
- therapy/query.py
> Handle whitespace

- Dockerfile
> Adds dockerfile #123

- setup.py
- tests/unit/test_query.py
- therapy/__init__.py
- therapy/query.py
- therapy/schemas.py
> therapy_id -> id for therapy descriptor

- dynamodb_revisions/add_xref_lookup.py
- tests/unit/data/therapies.json
- tests/unit/test_chemidplus_source.py
- tests/unit/test_drugbank_source.py
- tests/unit/test_ncit_source.py
- tests/unit/test_query.py
- tests/unit/test_rxnorm_source.py
- tests/unit/test_wikidata_source.py
- therapy/database.py
- therapy/etl/chemidplus.py
- therapy/etl/drugbank.py
- therapy/etl/ncit.py
- therapy/etl/rxnorm.py
- therapy/etl/wikidata.py
- therapy/query.py
- therapy/schemas.py
> Xref lookup

- tests/unit/data/therapies.json
- tests/unit/test_database.py
- tests/unit/test_merge.py
- tests/unit/test_query.py
- therapy/version.py
- tox.ini
> Update spiramycin tests

- Pipfile
- requirements-dev.txt
- requirements.txt
- setup.cfg
- therapy/main.py
They finally merged this PR into FastAPI over the weekend! Now our work is truly done
> Enable parameter entry in swaggerui by default

- .github/workflows/github-actions.yml
- setup.cfg
- therapy/__init__.py
> CI: Install deps with pip

- .github/workflows/github-actions.yml
(Should've thought of this beforehand)
> CI: Don't install dependencies twice

- therapy/etl/rxnorm.py
> fix(rxnorm): remove NOCODE IDs

- README.md
- tests/unit/data/metadata.json
- tests/unit/data/therapies.json
- tests/unit/test_guidetopharmacology.py
- therapy/etl/base.py
- therapy/etl/guidetopharmacology.py
- close #253 
- update data import for new gtop file structure
> fix(gtop): handle guide to pharmacology data updates

- therapy/etl/rxnorm.py
> fix(rxnorm): remove NOCODE id's

- therapy/etl/rxnorm.py
> feat: use new RxNorm download method

- therapy/etl/ncit.py
- therapy/schemas.py
#320  and  #318 for 0.3x branch
> refactor: remove unused schema elements

- .github/workflows/checks.yaml
- .github/workflows/release.yml
> ci: resolve GH Actions version warnings

- tests/unit/test_guidetopharmacology.py
- therapy/etl/guidetopharmacology.py
> fix: remove script tags from gtop therapy names

- setup.cfg
Addresses #335 for staging branch
> fix: pypi package should include all files in etl/ (staging)

- setup.cfg
- therapy/version.py
Close #335 
Tested on: https://test.pypi.org/project/thera-py/0.3.9/
`pip install -i https://test.pypi.org/simple/ thera-py==0.3.9 --no-deps`
> fix: pypi package should include all files in etl/

- Pipfile
- requirements-dev.txt
- requirements.txt
- setup.cfg
Addresses #311 for staging branch
> build: update disease normalizer to >=0.3.1

- Pipfile
- requirements-dev.txt
- requirements.txt
- setup.cfg
> build: update disease normalizer to ~0.2.19

- .github/workflows/checks.yaml
- tests/conftest.py
- tests/scripts/build_disease_normalizer_data.py
- tests/unit/test_disease_indication.py
> test: Add test for DiseaseIndicationBase

- tests/conftest.py
- tests/unit/test_chembl.py
- tests/unit/test_chemidplus.py
- tests/unit/test_drugbank.py
- tests/unit/test_drugsatfda.py
- tests/unit/test_guidetopharmacology.py
- tests/unit/test_hemonc.py
- tests/unit/test_ncit.py
- tests/unit/test_query.py
- tests/unit/test_rxnorm.py
- tests/unit/test_wikidata.py
- therapy/cli.py
- therapy/etl/base.py
- therapy/query.py
- therapy/schemas.py
- `Drug` -> `Therapy`
- `normalizers` -> `sources` in CLI
not necessarily related issues, but both have been bugging me so I did them both
> feat!: improve interface wording

- src/therapy/cli.py
- src/therapy/database.py
- src/therapy/etl/chembl.py
- src/therapy/etl/guidetopharmacology.py
- src/therapy/etl/hemonc.py
- src/therapy/etl/rxnorm.py
- src/therapy/schemas.py
- tests/unit/test_chembl.py
- tests/unit/test_chemidplus.py
- tests/unit/test_disease_indication.py
- tests/unit/test_drugbank.py
- tests/unit/test_drugsatfda.py
- tests/unit/test_hemonc.py
- tests/unit/test_query.py
so gh actions will give us that check ✔️
> style: remove unnecessary noqa: E501

- README.md
- src/therapy/database/database.py
- src/therapy/database/dynamodb.py
- src/therapy/etl/base.py
- src/therapy/etl/guidetopharmacology.py
- src/therapy/etl/wikidata.py
- src/therapy/main.py
- src/therapy/query.py
- src/therapy/schemas.py
- tests/conftest.py
- tests/unit/test_chembl.py
- tests/unit/test_chemidplus.py
- tests/unit/test_drugbank.py
- tests/unit/test_drugsatfda.py
- tests/unit/test_guidetopharmacology.py
- tests/unit/test_hemonc.py
- tests/unit/test_ncit.py
- tests/unit/test_query.py
- tests/unit/test_rxnorm.py
- tests/unit/test_wikidata.py
A few misc schema fixes including
* Correct error names
* Pydantic serialization wasn't working correctly for source metadata on the normalized endpoint for some reason
* Drug -> Therapy (already done on VRS 1.x branch)
> feat!: refine schemas

- src/therapy/main.py
- src/therapy/query.py
- src/therapy/schemas.py
- tests/conftest.py
- tests/unit/test_query.py
See eg https://github.com/cancervariants/gene-normalization/pull/244
> feat!: remove search result formatting option

- README.md
close #396 
* Add link to harvard dataverse website
> docs: update hemonc instructions in readme

- src/therapy/etl/guidetopharmacology.py
close #315 
not actually terribly urgent (I manually fixed my local DB already, there are only two cases where this matters)
> fix: handle multiple CHEBI IDs on a row

- .github/workflows/checks.yaml
- pyproject.toml
- src/therapy/database/dynamodb.py
- src/therapy/etl/wikidata.py
- src/therapy/query.py
- tests/scripts/build_wikidata_data.py
* https://github.com/GenomicMedLab/software-templates/pull/66
> build!: require python >= 3.11

- src/therapy/etl/wikidata.py
* not particularly motivated to add a note to the README for now -- would prefer to avoid doing so until we write actual docs for this thing
> fix: resolve user agent warning in wikibase

- .github/workflows/checks.yaml
- README.md
- pyproject.toml
> chore!: rename optional dependency

- pyproject.toml
Last PR before new therapy release
> build: bump wags-tails version to ~=0.2.2

- pyproject.toml
- src/therapy/query.py
- src/therapy/schemas.py
- tests/data/fixtures/query_fixtures.json
- tests/unit/test_query.py
* `label` -> `name` in `MappableConcept`
> build!: update ga4gh.vrs

- .github/workflows/checks.yaml
- .pre-commit-config.yaml
small changes that I must've previously missed
> cicd: update precommit

- pyproject.toml
* incorporate latest wags-tails NCIt version lookup fix
* update disease-normalizer
> build: update dependencies

- src/therapy/cli.py
- src/therapy/etl/hemonc.py
* use latest disease ETL api
* add a more informative error response if hemonc dataverse key is unset
> fix: handle ETL issues du jour

- pyproject.toml
- src/therapy/etl/base.py
- src/therapy/query.py
- src/therapy/schemas.py
- tests/data/fixtures/query_fixtures.json
- tests/unit/test_query.py
close #471
* Also introduces deepdiff to simplify equality check in tests
> feat!: use VRS 2.0.1 models
